name: mapbox_gl
description: A Flutter plugin for integrating Mapbox Maps inside a Flutter application on Android, iOS and web platfroms.
version: 0.17.1
homepage: https://github.com/jon-mly/mapbox-gl

dependencies:
  flutter:
    sdk: flutter
  mapbox_gl_platform_interface:
    path: ./mapbox_gl_platform_interface
  mapbox_gl_web:
    path: ./mapbox_gl_web
#  mapbox_gl_platform_interface:
#    git:
#      url: https://github.com/jon-mly/mapbox_gl.git
#      path: mapbox_gl_platform_interface
#  mapbox_gl_web:
#    git:
#      url: https://github.com/jon-mly/mapbox_gl.git
#      path: mapbox_gl_web
  collection: ^1.15.0

#dependency_overrides:
#  mapbox_gl_platform_interface:
#    path: ./mapbox_gl_platform_interface
#  mapbox_gl_web:
#    path: ./mapbox_gl_web

flutter:
  plugin:
    platforms:
      android:
        package: com.mapbox.mapboxgl
        pluginClass: MapboxMapsPlugin
      ios:
        pluginClass: MapboxMapsPlugin
      web:
        default_package: mapbox_gl_web

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: ">=2.0.0"
