name: mapbox_gl_platform_interface
description: A common platform interface for the mapbox_gl plugin.
version: 0.17.0
homepage: https://github.com/jon-mly/mapbox-gl

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.15.0

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: ">=2.0.0"
